#!/bin/bash
# continued Massive Network Game Object Server
# autorestart Script

crashcount=0

case $1 in
    start )
        screen -dmS run-authserver $PWD/$0 detached
        echo "AuthServer started"
    ;;
    detached )
        while :
        do
                echo `date` >> crash.log
                cmd="./authserver"
                $cmd
                status=$?
                echo "Status after downtime is: $status"
                mv Server.log Server$(date +%F-%H:%M).log && touch AuthServer.log
                if [ "$status" == "2" ]; then
                   echo `date` ", AuthServer restarted."
                elif [ "$status" == "0" ]; then
                   echo "date" ", MaNGOS realm shut down."
                   exit 0
                else
                   mv crash.log $(date +%F-%H:%M).log && touch crash.log
                   echo "date" ", AuthServer crashed."
                   ((crashcount=crashcount+1))
                   if [ "$crashcount" -gt 50 ]; then
                      exit 0
                   fi
                fi
        done
        ;;
esac
