# Select WoW Expansion (Default: Vanilla)
set(BUILD "Vanilla" CACHE STRING "Select the WoW Expansion to build the core for")
set_property(CACHE BUILD PROPERTY STRINGS Vanilla TBC WOTLK Cataclysm MoP WoD Legion BfA SL DF TWW)

message(STATUS "Building Core for Expansion: ${BUILD}")

# Build numbers
set(BUILD_NUMBERS_Vanilla "5875")
set(BUILD_NUMBERS_TBC "8606")
set(BUILD_NUMBERS_WOTLK "12340")
set(BUILD_NUMBERS_Cataclysm "15595")
set(BUILD_NUMBERS_MoP "18414")
set(BUILD_NUMBERS_WoD "21742")
set(BUILD_NUMBERS_Legion "26124;26365;26972")
set(BUILD_NUMBERS_BfA "35662")
set(BUILD_NUMBERS_SL "45745")
set(BUILD_NUMBERS_DF "55664")
set(BUILD_NUMBERS_TWW "61122")

# Set definitions based on selected build
if(BUILD STREQUAL "Vanilla")
    set(BUILD_VERSION_MACRO BUILD_VERSION_VANILLA)
    set(BUILD_NUMBERS ${BUILD_NUMBERS_Vanilla})
elseif(BUILD STREQUAL "TBC")
    set(BUILD_VERSION_MACRO BUILD_VERSION_TBC)
    set(BUILD_NUMBERS ${BUILD_NUMBERS_TBC})
elseif(BUILD STREQUAL "WOTLK")
    set(BUILD_VERSION_MACRO BUILD_VERSION_WOTLK)
    set(BUILD_NUMBERS ${BUILD_NUMBERS_WOTLK})
elseif(BUILD STREQUAL "Cataclysm")
    set(BUILD_VERSION_MACRO BUILD_VERSION_CATA)
    set(BUILD_NUMBERS ${BUILD_NUMBERS_Cataclysm})
elseif(BUILD STREQUAL "MoP")
    set(BUILD_VERSION_MACRO BUILD_VERSION_MOP)
    set(BUILD_NUMBERS ${BUILD_NUMBERS_MoP})
elseif(BUILD STREQUAL "WoD")
    set(BUILD_VERSION_MACRO BUILD_VERSION_WOD)
    set(BUILD_NUMBERS ${BUILD_NUMBERS_WoD})
elseif(BUILD STREQUAL "Legion")
    set(BUILD_VERSION_MACRO BUILD_VERSION_LEGION)
    set(BUILD_NUMBERS ${BUILD_NUMBERS_Legion})
elseif(BUILD STREQUAL "BfA")
    set(BUILD_VERSION_MACRO BUILD_VERSION_BFA)
    set(BUILD_NUMBERS ${BUILD_NUMBERS_BfA})
elseif(BUILD STREQUAL "SL")
    set(BUILD_VERSION_MACRO BUILD_VERSION_SL)
    set(BUILD_NUMBERS ${BUILD_NUMBERS_SL})
elseif(BUILD STREQUAL "DF")
    set(BUILD_VERSION_MACRO BUILD_VERSION_DF)
    set(BUILD_NUMBERS ${BUILD_NUMBERS_DF})
elseif(BUILD STREQUAL "TWW")
    set(BUILD_VERSION_MACRO BUILD_VERSION_TWW)
    set(BUILD_NUMBERS ${BUILD_NUMBERS_TWW})
else()
    message(FATAL_ERROR "Unsupported expansion selected: ${BUILD}")
endif()

# Output info
message(STATUS "Using build numbers: ${BUILD_NUMBERS}")
string(REPLACE ";" " " BUILD_NUMBERS_STR "${BUILD_NUMBERS}")

# Save macros globally to use in target_compile_definitions()
set(GLOBAL_BUILD_VERSION_MACRO ${BUILD_VERSION_MACRO} CACHE INTERNAL "Build version macro (for target_compile_definitions)")
set(GLOBAL_BUILD_NUMBERS "${BUILD_NUMBERS_STR}" CACHE INTERNAL "Build numbers macro (for target_compile_definitions)")

# For revision.h use
set(BUILD_SELECTED_VERSION "${BUILD}" CACHE INTERNAL "Selected expansion for revision.h")
