name: macOS Build

on: [push]

env:
  BUILD_TYPE: Release
  REPO_DIR: ${{ github.workspace }}
  BUILD_DIR: ${{ github.workspace }}/bin/builddir
  BOOST_VERSION: "1.83.0"
  BOOST_PLATFORM_VERSION: "13"  # macOS 13 runners
  BOOST_ARCH: x86  # macOS = x86_64 (Apple Silicon später anders behandeln)

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.REPO_DIR }}

      - name: Setup Build Environment
        run: |
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          cmake -E make_directory ${{ env.BUILD_DIR }}

      - name: Install Boost
        uses: MarkusJx/install-boost@v2.5.0
        id: install-boost
        with:
          boost_version: ${{ env.BOOST_VERSION }}
          platform_version: ${{ env.BOOST_PLATFORM_VERSION }}
          toolset: clang
          arch: ${{ env.BOOST_ARCH }}

      - name: Verify Boost Installation
        run: |
          echo "Boost Root: ${{ steps.install-boost.outputs.BOOST_ROOT }}"
          ls -l ${{ steps.install-boost.outputs.BOOST_ROOT }}/include/boost
          ls -l ${{ steps.install-boost.outputs.BOOST_ROOT }}/lib

      - name: Configure with CMake
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
          BOOST_INCLUDEDIR: ${{ steps.install-boost.outputs.BOOST_ROOT }}/include
          BOOST_LIBRARYDIR: ${{ steps.install-boost.outputs.BOOST_ROOT }}/lib
        run: >
          cmake
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install
          -DBoost_NO_BOOST_CMAKE=ON
          -DBoost_NO_SYSTEM_PATHS=ON
          -DBOOST_ROOT=${{ env.BOOST_ROOT }}
          -DBOOST_INCLUDEDIR=${{ env.BOOST_INCLUDEDIR }}
          -DBOOST_LIBRARYDIR=${{ env.BOOST_LIBRARYDIR }}
          -B ${{ env.BUILD_DIR }}
          -S ${{ env.REPO_DIR }}

      - name: Build
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }}

      - name: Install
        run: cmake --install ${{ env.BUILD_DIR }}
