name: Ubuntu Build

on: [push]

env:
  BUILD_TYPE: Release
  REPO_DIR: ${{ github.workspace }}
  BUILD_DIR: ${{ github.workspace }}/bin/builddir
  BOOST_VERSION: "1.78.0"
  BOOST_PLATFORM_VERSION: "22.04"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            COMPILER_CC: gcc-12
            COMPILER_PP: g++-12
            USE_PCH: ON
            EXTRA_BUILD: ""

          - os: ubuntu-22.04
            COMPILER_CC: clang
            COMPILER_PP: clang++
            USE_PCH: ON
            EXTRA_BUILD: ""

          - os: ubuntu-22.04
            COMPILER_CC: clang
            COMPILER_PP: clang++
            USE_PCH: OFF
            EXTRA_BUILD: ""

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          path: ${{ env.REPO_DIR }}

      - name: Set Build Environment
        run: |
          echo "GITHUB_SHORT_REV=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "ARCHIVE_FILENAME=${{ github.event.repository.name }}-$(git rev-parse --short HEAD).zip" >> $GITHUB_ENV
          echo "CC=${{ matrix.COMPILER_CC }}" >> $GITHUB_ENV
          echo "CXX=${{ matrix.COMPILER_PP }}" >> $GITHUB_ENV
          cmake -E make_directory ${{ env.BUILD_DIR }}

      - name: Install Boost 1.78.0
        uses: MarkusJx/install-boost@v2.5.0
        id: install-boost
        with:
          boost_version: ${{ env.BOOST_VERSION }}
          platform_version: ${{ env.BOOST_PLATFORM_VERSION }}
          arch: x86

      - name: Verify Boost Installation
        run: |
          echo "Boost Root: ${{ steps.install-boost.outputs.BOOST_ROOT }}"
          ls -l ${{ steps.install-boost.outputs.BOOST_ROOT }}/include/boost
          ls -l ${{ steps.install-boost.outputs.BOOST_ROOT }}/lib

      - name: Configure Project with CMake
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
          BOOST_INCLUDEDIR: ${{ steps.install-boost.outputs.BOOST_ROOT }}/include
          BOOST_LIBRARYDIR: ${{ steps.install-boost.outputs.BOOST_ROOT }}/lib
          USE_PCH: ${{ matrix.USE_PCH }}
          EXTRA_BUILD: ${{ matrix.EXTRA_BUILD }}
        run: >
          cmake
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          -DCMAKE_INSTALL_PREFIX=/home/runner/work
          -DPCH=${{ env.USE_PCH }}
          -DBoost_NO_BOOST_CMAKE=ON
          -DBOOST_ROOT=${{ env.BOOST_ROOT }}
          -DBOOST_INCLUDEDIR=${{ env.BOOST_INCLUDEDIR }}
          -DBOOST_LIBRARYDIR=${{ env.BOOST_LIBRARYDIR }}
          ${{ env.EXTRA_BUILD }}
          -B ${{ env.BUILD_DIR }}
          -S ${{ env.REPO_DIR }}

      - name: Build Project
        env:
          MAKEFLAGS: "-j8"
        run: |
          cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }}
          cmake --install ${{ env.BUILD_DIR }}
